
schema: https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json
version: 0.1.0
changelog:
  0.1.0: Add working train.yaml file
  0.0.1: initialize the model package structure
monai_version: 1.1.0
pytorch_version: 1.12.0
numpy_version: 1.22.3
optional_packages_version:
  fire: 0.4.0
  pytorch-ignite: 0.4.10
  nibabel: 4.0.10
task: Organ Segmentation
description: A small clone of the totalsegmentator model
authors: Keno Bressem
copyright: Copyright (c) Keno Bressem
network_data_format:
  inputs:
    image:
      type: image
      format: Density
      modality: CT
      num_channels: 1
      spatial_shape:
        - 64
        - 64
        - 64
      dtype: float32
      value_range:
        - 0
        - 1
      is_patch_data: true
      channel_def:
        "0": image
  outputs:
    pred:
      type: image
      format: segmentation
      num_channels: 104
      spatial_shape:
        - 64
        - 64
        - 64
      dtype: float32
      value_range:
        - 0
        - 1
      is_patch_data: true
      channel_def:
        "0": background
        "1": kidney
