schema: https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json
version: 0.1.0
changelog:
  0.1.0: Add working train.yaml file
  0.0.1: initialize the model package structure
monai_version: 1.1.0
pytorch_version: 1.12.0
numpy_version: 1.22.3
optional_packages_version:
  fire: 0.4.0
  pytorch-ignite: 0.4.10
  nibabel: 4.0.10
task: Organ Segmentation
description: A small clone of the totalsegmentator model
authors: Keno Bressem
copyright: Copyright_(c) Keno Bressem
network_data_format:
  inputs:
    image:
      type: image
      format: Density
      modality: CT
      num_channels: 1
      spatial_shape:
        - 64
        - 64
        - 64
      dtype: float32
      value_range:
        - 0
        - 1
      is_patch_data: true
      channel_def:
        "0": image
  outputs:
    pred:
      type: image
      format: segmentation
      num_channels: 104
      spatial_shape:
        - 64
        - 64
        - 64
      dtype: float32
      value_range:
        - 0
        - 1
      is_patch_data: true
      channel_def:
        - 0: background
        - 1: spleen
        - 2: right_kidney
        - 3: left_kidney
        - 4: gallbladder
        - 5: liver
        - 6: stomach
        - 7: aorta
        - 8: inferior_vena_cava
        - 9: portal_vein_and_splenic_vein
        - 10: pancreas
        - 11: right_adrenal_gland
        - 12: left_adrenal_gland
        - 13: left_upper_lobe_of_lung
        - 14: left_lower_lobe_of_lung
        - 15: right_upper_lobe_of_lung
        - 16: right_middle_lobe_of_lung
        - 17: right_lower_lobe_of_lung
        - 18: vertebra_L5
        - 19: vertebra_L4
        - 20: vertebra_L3
        - 21: vertebra_L2
        - 22: vertebra_L1
        - 23: vertebra_T12
        - 24: vertebra_T11
        - 25: vertebra_T10
        - 26: vertebra_T9
        - 27: vertebra_T8
        - 28: vertebra_T7
        - 29: vertebra_T6
        - 30: vertebra_T5
        - 31: vertebra_T4
        - 32: vertebra_T3
        - 33: vertebra_T2
        - 34: vertebra_T1
        - 35: vertebra_C7
        - 36: vertebra_C6
        - 37: vertebra_C5
        - 38: vertebra_C4
        - 39: vertebra_C3
        - 40: vertebra_C2
        - 41: vertebra_C1
        - 42: esophagus
        - 43: trachea
        - 44: myocardium_of_the_heart
        - 45: left_atrium_of_the_heart
        - 46: left_ventricle_of_the_heart
        - 47: right_atrium_of_the_heart
        - 48: right_ventricle_of_the_heart
        - 49: pulmonary_artery
        - 50: brain
        - 51: left_iliac_artery
        - 52: right_iliac_artery
        - 53: left_iliac_vein
        - 54: right_iliac_vein
        - 55: small_bowel
        - 56: duodenum
        - 57: colon
        - 58: left_rib_1
        - 59: left_rib_2
        - 60: left_rib_3
        - 61: left_rib_4
        - 62: left_rib_5
        - 63: left_rib_6
        - 64: left_rib_7
        - 65: left_rib_8
        - 66: left_rib_9
        - 67: left_rib_10
        - 68: left_rib_11
        - 69: left_rib_12
        - 70: right_rib_1
        - 71: right_rib_2
        - 72: right_rib_3
        - 73: right_rib_4
        - 74: right_rib_5
        - 75: right_rib_6
        - 76: right_rib_7
        - 77: right_rib_8
        - 78: right_rib_9
        - 79: right_rib_10
        - 80: right_rib_11
        - 81: right_rib_12
        - 82: left_humerus
        - 83: right_humerus
        - 84: left_scapula
        - 85: right_scapula
        - 86: left_clavicle
        - 87: right_clavicle
        - 88: left_femur
        - 89: right_femur
        - 90: left_hip_joint
        - 91: right_hip_joint
        - 92: sacrum
        - 93: face
        - 94: left_gluteus_maximus
        - 95: right_gluteus_maximus
        - 96: left_gluteus_medius
        - 97: right_gluteus_medius
        - 98: left_gluteus_minimus
        - 99: right_gluteus_minimus
        - 100: left_autochthonous_muscle
        - 101: right_autochthonous_muscle
        - 102: left_iliopsoas_muscle
        - 103: right_iliopsoas_muscle
        - 104: urinary_bladder
